import moo from "moo";

const tokens = {
  WS: /[ \t]/u,
  NL: { match: /\r?\n|\r/u, lineBreaks: true },
  comment: /#.*?(\r?\n|\r)?$/u,
  true: { match: /^true$/, value: () => true },
  false: { match: /^false$/, value: () => false },
  nil: { match: /^nil$/, value: () => null },
  number: {
    match: /^([1-9]\d*|0|[1-9]\d*\.|0\.|\.)\d*?([eE][+-]?\d+)?$/u,
    value: (n) => Number(n),
  },
  hexlit: /0[xX][0-9a-fA-F]+/u,
  octlit: /0[oO][0-7]+/,
  binlit: /0[bB][01]+/,
  symbol: {
    match: /[\p{L}_$][\p{LN}_$\?\!=-\*\/<>\+]*/u,
    type: moo.keywords(
      Object.fromEntries(
        [
          "let",
          "rec",
          "in",
          "and",
          "if",
          "then",
          "else",
          "fun",
          "when",
          "for",
          "type",
          "match",
          "with",
          "module",
          "private",
          "mutable",
          "not",
          "begin",
          "do",
          "end",
        ].map((w) => [w, w])
      )
    ),
  },
  string: { match: /^\"(?:\\?+\s\S)*?\"$/u },
  apply: "->",
  pipe: "|>",
  concat: "++",
  plus: "+",
  minus: "-",
  exp: "**",
  mul: "*",
  div: "/",
  intdiv: "//",
  mod: "%",
  rshift: ">>>",
  lshift: "<<<",
  bwxor: "^",
  bwand: "&",
  bwor: "|",
  bwnot: "~",
  lt: "<",
  gt: ">",
  lte: "<=",
  rte: ">=",
  eq: "==",
  ne: "!=",
  andop: "&&",
  or: "||",
  lparen: "(",
  rparen: ")",
  lbracket: "[",
  rbracket: "]",
  lbrace: "{",
  rbrace: "}",
  assign: ":=",
  bind: "=",
  colon: ":",
  semi: ";",
  quote: "'",
  tick: "`",
  at: "@",
  composer: ">>",
  composel: "<<",
  comma: ",",
  dot: ".",
  quest: "?",
  bang: "!",
};
